import "server-only"

import { createHash } from "node:crypto"

import type {
  AccountInsert,
  ClientInsert,
  CommunicationLogInsert,
  ComplianceRecordInsert,
  DocumentInsert,
  FeeScheduleInsert,
  GoalInsert,
  HoldingInsert,
  HouseholdInsert,
  LeadInsert,
  MeetingInsert,
  OpportunityInsert,
  PortfolioInsert,
  ProfileInsert,
  TaskInsert,
  TransactionInsert,
} from "@/lib/database.types"

function seededUuid(userId: string, key: string) {
  const hex = createHash("sha256").update(`${userId}:${key}`).digest("hex").slice(0, 32)

  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`
}

function dateOffset(days: number) {
  const date = new Date()
  date.setDate(date.getDate() + days)
  return date.toISOString().slice(0, 10)
}

function timestampOffset(days: number, hour = 10, minute = 0) {
  const date = new Date()
  date.setDate(date.getDate() + days)
  date.setHours(hour, minute, 0, 0)
  return date.toISOString()
}

function titleCaseWords(value: string) {
  return value
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join(" ")
}

function deriveInvestorIdentity({
  city,
  email,
  fullName,
  phone,
}: {
  city?: string | null
  email: string | null
  fullName: string | null
  phone?: string | null
}) {
  const normalizedEmail = email?.trim().toLowerCase() ?? null
  const fallbackName =
    normalizedEmail?.split("@")[0]?.replace(/[._-]+/g, " ") ?? "Demo Investor"
  const normalizedName = titleCaseWords(fullName?.trim() || fallbackName)
  const nameParts = normalizedName.split(/\s+/).filter(Boolean)
  const firstName = nameParts[0] ?? "Demo"
  const lastName = nameParts.length > 1 ? nameParts.slice(1).join(" ") : "Investor"
  const householdLabel = lastName !== "Investor" ? lastName : firstName
  const householdName =
    lastName !== "Investor" ? `${householdLabel} Family Office` : `${firstName} Household`

  return {
    city: city?.trim() || "Mumbai",
    displayName: `${firstName} ${lastName}`.trim(),
    email:
      normalizedEmail ??
      `${firstName.toLowerCase()}.${householdLabel.toLowerCase()}@example.com`,
    firstName,
    growthPortfolioName:
      lastName !== "Investor"
        ? `${householdLabel} Growth Portfolio`
        : `${firstName} Growth Portfolio`,
    householdName,
    incomePortfolioName:
      lastName !== "Investor"
        ? `${householdLabel} Income Portfolio`
        : `${firstName} Income Portfolio`,
    lastName,
    phone: phone?.trim() || "+91 98765 43210",
    reviewSubjectLabel: lastName !== "Investor" ? householdLabel : `${firstName} Household`,
  }
}

export function buildDemoWorkspace(
  userId: string,
  email: string | null,
  fullName: string | null,
  options?: {
    city?: string | null
    phone?: string | null
  },
) {
  const investorIdentity = deriveInvestorIdentity({
    city: options?.city,
    email,
    fullName,
    phone: options?.phone,
  })
  const accountPrefix = userId.replaceAll("-", "").slice(0, 6).toUpperCase()
  const householdIds = {
    iyer: seededUuid(userId, "household-iyer"),
    khandelwal: seededUuid(userId, "household-khandelwal"),
    mehta: seededUuid(userId, "household-mehta"),
    patel: seededUuid(userId, "household-patel"),
    sharma: seededUuid(userId, "household-sharma"),
  }

  const clientIds = {
    anilMehta: seededUuid(userId, "client-anil-mehta"),
    deepakSharma: seededUuid(userId, "client-deepak-sharma"),
    lakshmiIyer: seededUuid(userId, "client-lakshmi-iyer"),
    meenaPatel: seededUuid(userId, "client-meena-patel"),
    priyaKhandelwal: seededUuid(userId, "client-priya-khandelwal"),
    rajeshPatel: seededUuid(userId, "client-rajesh-patel"),
    sunitaSharma: seededUuid(userId, "client-sunita-sharma"),
    venkateshIyer: seededUuid(userId, "client-venkatesh-iyer"),
  }

  const portfolioIds = {
    iyerPreservation: seededUuid(userId, "portfolio-iyer-preservation"),
    khandelwalIncome: seededUuid(userId, "portfolio-khandelwal-income"),
    mehtaGrowth: seededUuid(userId, "portfolio-mehta-growth"),
    patelGrowth: seededUuid(userId, "portfolio-patel-growth"),
    patelIncome: seededUuid(userId, "portfolio-patel-income"),
    sharmaRetirement: seededUuid(userId, "portfolio-sharma-retirement"),
  }

  const accountIds = {
    iyerPreservation: seededUuid(userId, "account-iyer-preservation"),
    khandelwalIncome: seededUuid(userId, "account-khandelwal-income"),
    mehtaGrowth: seededUuid(userId, "account-mehta-growth"),
    patelGrowth: seededUuid(userId, "account-patel-growth"),
    patelIncome: seededUuid(userId, "account-patel-income"),
    sharmaRetirement: seededUuid(userId, "account-sharma-retirement"),
  }

  const profile: ProfileInsert = {
    city: investorIdentity.city,
    email: investorIdentity.email,
    full_name: fullName?.trim() || investorIdentity.displayName,
    id: userId,
    organization_name: "WealthFlow Capital Advisors",
    phone: options?.phone?.trim() || "+91 98765 40000",
    role: "advisor",
  }

  const households: HouseholdInsert[] = [
    {
      advisor_id: userId,
      id: householdIds.patel,
      name: investorIdentity.householdName,
      next_review_date: dateOffset(14),
      notes: `Primary investor household for ${investorIdentity.displayName}, focused on diversified long-term wealth compounding.`,
      risk_profile: "Balanced Growth",
      segment: "HNI",
      status: "active",
      total_aum: 92_000_000,
    },
    {
      advisor_id: userId,
      id: householdIds.iyer,
      name: "Iyer Legacy Trust",
      next_review_date: dateOffset(21),
      notes: "Succession and preservation mandate for trust beneficiaries.",
      risk_profile: "Capital Preservation",
      segment: "UHNI",
      status: "active",
      total_aum: 118_000_000,
    },
    {
      advisor_id: userId,
      id: householdIds.mehta,
      name: "Mehta Entrepreneurs",
      next_review_date: dateOffset(9),
      notes: "Liquidity planning and high-growth equity allocation for founders.",
      risk_profile: "Aggressive Growth",
      segment: "HNI",
      status: "active",
      total_aum: 54_000_000,
    },
    {
      advisor_id: userId,
      id: householdIds.khandelwal,
      name: "Khandelwal Advisory Desk",
      next_review_date: dateOffset(26),
      notes: "Advisory branch treasury and billing oversight workspace.",
      risk_profile: "Income Focused",
      segment: "Advisory",
      status: "active",
      total_aum: 62_000_000,
    },
    {
      advisor_id: userId,
      id: householdIds.sharma,
      name: "Sharma Retirement Fund",
      next_review_date: dateOffset(31),
      notes: "Retirement corpus and income-drawdown planning for senior executives.",
      risk_profile: "Conservative",
      segment: "HNI",
      status: "active",
      total_aum: 38_000_000,
    },
  ]

  const clients: ClientInsert[] = [
    {
      city: investorIdentity.city,
      date_of_birth: "1974-08-12",
      email: investorIdentity.email,
      first_name: investorIdentity.firstName,
      household_id: householdIds.patel,
      id: clientIds.rajeshPatel,
      kyc_status: "verified",
      last_name: investorIdentity.lastName,
      onboarding_stage: "active",
      owner_id: userId,
      pan_number: "ABCPD1234E",
      phone: investorIdentity.phone,
    },
    {
      city: investorIdentity.city,
      date_of_birth: "1978-02-19",
      email: null,
      first_name: "Household",
      household_id: householdIds.patel,
      id: clientIds.meenaPatel,
      kyc_status: "verified",
      last_name: "Member",
      onboarding_stage: "active",
      owner_id: userId,
      pan_number: "ABCPD1235F",
      phone: null,
    },
    {
      city: "Chennai",
      date_of_birth: "1968-05-04",
      email: "venkatesh.iyer@example.com",
      first_name: "Venkatesh",
      household_id: householdIds.iyer,
      id: clientIds.venkateshIyer,
      kyc_status: "verified",
      last_name: "Iyer",
      onboarding_stage: "active",
      owner_id: userId,
      pan_number: "EFGHI2345J",
      phone: "+91 98765 43212",
    },
    {
      city: "Chennai",
      date_of_birth: "1972-11-23",
      email: "lakshmi.iyer@example.com",
      first_name: "Lakshmi",
      household_id: householdIds.iyer,
      id: clientIds.lakshmiIyer,
      kyc_status: "pending",
      last_name: "Iyer",
      onboarding_stage: "active",
      owner_id: userId,
      pan_number: "EFGHI2346K",
      phone: "+91 98765 43213",
    },
    {
      city: "Mumbai",
      date_of_birth: "1984-04-14",
      email: "anil.mehta@example.com",
      first_name: "Anil",
      household_id: householdIds.mehta,
      id: clientIds.anilMehta,
      kyc_status: "verified",
      last_name: "Mehta",
      onboarding_stage: "active",
      owner_id: userId,
      pan_number: "KLMNO3456P",
      phone: "+91 98765 43214",
    },
    {
      city: "Pune",
      date_of_birth: "1986-09-07",
      email: "priya.khandelwal@example.com",
      first_name: "Priya",
      household_id: householdIds.khandelwal,
      id: clientIds.priyaKhandelwal,
      kyc_status: "pending",
      last_name: "Khandelwal",
      onboarding_stage: "prospect",
      owner_id: userId,
      pan_number: "PQRST4567U",
      phone: "+91 98765 43215",
    },
    {
      city: "Delhi",
      date_of_birth: "1965-03-09",
      email: "deepak.sharma@example.com",
      first_name: "Deepak",
      household_id: householdIds.sharma,
      id: clientIds.deepakSharma,
      kyc_status: "verified",
      last_name: "Sharma",
      onboarding_stage: "active",
      owner_id: userId,
      pan_number: "UVWXY5678Z",
      phone: "+91 98765 43216",
    },
    {
      city: "Delhi",
      date_of_birth: "1967-12-18",
      email: "sunita.sharma@example.com",
      first_name: "Sunita",
      household_id: householdIds.sharma,
      id: clientIds.sunitaSharma,
      kyc_status: "expired",
      last_name: "Sharma",
      onboarding_stage: "active",
      owner_id: userId,
      pan_number: "UVWXY5679A",
      phone: "+91 98765 43217",
    },
  ]

  const portfolios: PortfolioInsert[] = [
    {
      benchmark: "Nifty 50 TRI",
      household_id: householdIds.patel,
      id: portfolioIds.patelGrowth,
      liquidity_ratio: 17.24,
      name: investorIdentity.growthPortfolioName,
      objective: "Long-term capital appreciation",
      performance_ytd: 14.2,
      total_value: 58_000_000,
      base_currency: "INR",
    },
    {
      benchmark: "CRISIL Composite Bond",
      household_id: householdIds.patel,
      id: portfolioIds.patelIncome,
      liquidity_ratio: 11.76,
      name: investorIdentity.incomePortfolioName,
      objective: "Stable income generation",
      performance_ytd: 8.5,
      total_value: 34_000_000,
      base_currency: "INR",
    },
    {
      benchmark: "Nifty 100 TRI",
      household_id: householdIds.iyer,
      id: portfolioIds.iyerPreservation,
      liquidity_ratio: 17.8,
      name: "Iyer Preservation Fund",
      objective: "Capital preservation with measured upside",
      performance_ytd: 6.8,
      total_value: 118_000_000,
      base_currency: "INR",
    },
    {
      benchmark: "Nifty Midcap 150 TRI",
      household_id: householdIds.mehta,
      id: portfolioIds.mehtaGrowth,
      liquidity_ratio: 9.26,
      name: "Mehta High Growth",
      objective: "Aggressive capital growth",
      performance_ytd: 22.5,
      total_value: 54_000_000,
      base_currency: "INR",
    },
    {
      benchmark: "CRISIL Short Term Bond",
      household_id: householdIds.khandelwal,
      id: portfolioIds.khandelwalIncome,
      liquidity_ratio: 12.9,
      name: "Khandelwal Income",
      objective: "Income generation with capital safety",
      performance_ytd: 9.2,
      total_value: 62_000_000,
      base_currency: "INR",
    },
    {
      benchmark: "Nifty 50 TRI",
      household_id: householdIds.sharma,
      id: portfolioIds.sharmaRetirement,
      liquidity_ratio: 13.16,
      name: "Sharma Retirement",
      objective: "Retirement corpus compounding",
      performance_ytd: 11.4,
      total_value: 38_000_000,
      base_currency: "INR",
    },
  ]

  const accounts: AccountInsert[] = [
    {
      account_number: `${accountPrefix}-PAT-GROWTH-01`,
      account_type: "demat",
      cash_balance: 10_000_000,
      custodian: "Zerodha",
      id: accountIds.patelGrowth,
      portfolio_id: portfolioIds.patelGrowth,
    },
    {
      account_number: `${accountPrefix}-PAT-INCOME-01`,
      account_type: "mutual_fund",
      cash_balance: 4_000_000,
      custodian: "CAMS",
      id: accountIds.patelIncome,
      portfolio_id: portfolioIds.patelIncome,
    },
    {
      account_number: `${accountPrefix}-IYER-PRES-01`,
      account_type: "pms",
      cash_balance: 21_000_000,
      custodian: "Kotak PMS",
      id: accountIds.iyerPreservation,
      portfolio_id: portfolioIds.iyerPreservation,
    },
    {
      account_number: `${accountPrefix}-MEHTA-GROW-01`,
      account_type: "demat",
      cash_balance: 5_000_000,
      custodian: "ICICI Direct",
      id: accountIds.mehtaGrowth,
      portfolio_id: portfolioIds.mehtaGrowth,
    },
    {
      account_number: `${accountPrefix}-KHAN-INCOME-01`,
      account_type: "bank",
      cash_balance: 8_000_000,
      custodian: "HDFC Bank",
      id: accountIds.khandelwalIncome,
      portfolio_id: portfolioIds.khandelwalIncome,
    },
    {
      account_number: `${accountPrefix}-SHARMA-RET-01`,
      account_type: "mutual_fund",
      cash_balance: 5_000_000,
      custodian: "Groww",
      id: accountIds.sharmaRetirement,
      portfolio_id: portfolioIds.sharmaRetirement,
    },
  ]

  const holdings: HoldingInsert[] = [
    {
      asset_class: "Large Cap Equity",
      average_cost: 2520,
      id: seededUuid(userId, "holding-patel-reliance"),
      market_price: 2880,
      market_value: 14_400_000,
      portfolio_id: portfolioIds.patelGrowth,
      security_name: "Reliance Industries Ltd",
      symbol: "RELIANCE",
      units: 5000,
      weight: null,
    },
    {
      asset_class: "Large Cap Equity",
      average_cost: 1480,
      id: seededUuid(userId, "holding-patel-hdfcbank"),
      market_price: 1720,
      market_value: 12_900_000,
      portfolio_id: portfolioIds.patelGrowth,
      security_name: "HDFC Bank Ltd",
      symbol: "HDFCBANK",
      units: 7500,
      weight: null,
    },
    {
      asset_class: "Large Cap Equity",
      average_cost: 3550,
      id: seededUuid(userId, "holding-patel-tcs"),
      market_price: 4000,
      market_value: 11_200_000,
      portfolio_id: portfolioIds.patelGrowth,
      security_name: "Tata Consultancy Services",
      symbol: "TCS",
      units: 2800,
      weight: null,
    },
    {
      asset_class: "Index ETF",
      average_cost: 175,
      id: seededUuid(userId, "holding-patel-niftybees"),
      market_price: 190,
      market_value: 9_500_000,
      portfolio_id: portfolioIds.patelGrowth,
      security_name: "Nippon Nifty 50 ETF",
      symbol: "NIFTYBEES",
      units: 50000,
      weight: null,
    },
    {
      asset_class: "Debt Mutual Fund",
      average_cost: 27.5,
      id: seededUuid(userId, "holding-patel-hdfcstbf"),
      market_price: 30,
      market_value: 12_000_000,
      portfolio_id: portfolioIds.patelIncome,
      security_name: "HDFC Short Term Debt Fund",
      symbol: "HDFCSTBF",
      units: 400000,
      weight: null,
    },
    {
      asset_class: "Liquid Fund",
      average_cost: 37.8,
      id: seededUuid(userId, "holding-patel-sbiliquid"),
      market_price: 40,
      market_value: 10_000_000,
      portfolio_id: portfolioIds.patelIncome,
      security_name: "SBI Liquid Fund",
      symbol: "SBILIQUID",
      units: 250000,
      weight: null,
    },
    {
      asset_class: "Debt ETF",
      average_cost: 38,
      id: seededUuid(userId, "holding-patel-bharatbond"),
      market_price: 40,
      market_value: 8_000_000,
      portfolio_id: portfolioIds.patelIncome,
      security_name: "Bharat Bond ETF",
      symbol: "BHARATBOND",
      units: 200000,
      weight: null,
    },
    {
      asset_class: "Gold",
      average_cost: 52,
      id: seededUuid(userId, "holding-iyer-goldbees"),
      market_price: 60,
      market_value: 15_000_000,
      portfolio_id: portfolioIds.iyerPreservation,
      security_name: "Nippon Gold ETF",
      symbol: "GOLDBEES",
      units: 250000,
      weight: null,
    },
    {
      asset_class: "Index ETF",
      average_cost: 180,
      id: seededUuid(userId, "holding-iyer-niftybees"),
      market_price: 200,
      market_value: 30_000_000,
      portfolio_id: portfolioIds.iyerPreservation,
      security_name: "Nippon Nifty 50 ETF",
      symbol: "NIFTYBEES",
      units: 150000,
      weight: null,
    },
    {
      asset_class: "Debt Mutual Fund",
      average_cost: 37,
      id: seededUuid(userId, "holding-iyer-icici-bond"),
      market_price: 40,
      market_value: 22_000_000,
      portfolio_id: portfolioIds.iyerPreservation,
      security_name: "ICICI Prudential Corporate Bond Fund",
      symbol: "ICICICORPBOND",
      units: 550000,
      weight: null,
    },
    {
      asset_class: "Government Securities",
      average_cost: 36,
      id: seededUuid(userId, "holding-iyer-sbigilt"),
      market_price: 40,
      market_value: 30_000_000,
      portfolio_id: portfolioIds.iyerPreservation,
      security_name: "SBI Magnum Gilt Fund",
      symbol: "SBIGILT",
      units: 750000,
      weight: null,
    },
    {
      asset_class: "Large Cap Equity",
      average_cost: 7600,
      id: seededUuid(userId, "holding-mehta-bajajfinance"),
      market_price: 9000,
      market_value: 18_000_000,
      portfolio_id: portfolioIds.mehtaGrowth,
      security_name: "Bajaj Finance Ltd",
      symbol: "BAJFINANCE",
      units: 2000,
      weight: null,
    },
    {
      asset_class: "Mid Cap Equity",
      average_cost: 790,
      id: seededUuid(userId, "holding-mehta-tatamotors"),
      market_price: 1000,
      market_value: 12_000_000,
      portfolio_id: portfolioIds.mehtaGrowth,
      security_name: "Tata Motors Ltd",
      symbol: "TATAMOTORS",
      units: 12000,
      weight: null,
    },
    {
      asset_class: "Mid Cap Mutual Fund",
      average_cost: 31,
      id: seededUuid(userId, "holding-mehta-pgimmid"),
      market_price: 38,
      market_value: 19_000_000,
      portfolio_id: portfolioIds.mehtaGrowth,
      security_name: "PGIM India Midcap Opportunities Fund",
      symbol: "PGIMMID",
      units: 500000,
      weight: null,
    },
    {
      asset_class: "Liquid Fund",
      average_cost: 37,
      id: seededUuid(userId, "holding-khandelwal-sbiliquid"),
      market_price: 40,
      market_value: 16_000_000,
      portfolio_id: portfolioIds.khandelwalIncome,
      security_name: "SBI Liquid Fund",
      symbol: "SBILIQUID",
      units: 400000,
      weight: null,
    },
    {
      asset_class: "Debt ETF",
      average_cost: 38,
      id: seededUuid(userId, "holding-khandelwal-bharatbond"),
      market_price: 40,
      market_value: 20_000_000,
      portfolio_id: portfolioIds.khandelwalIncome,
      security_name: "Bharat Bond ETF",
      symbol: "BHARATBOND",
      units: 500000,
      weight: null,
    },
    {
      asset_class: "Corporate Bond",
      average_cost: 36,
      id: seededUuid(userId, "holding-khandelwal-icici-corp"),
      market_price: 40,
      market_value: 18_000_000,
      portfolio_id: portfolioIds.khandelwalIncome,
      security_name: "ICICI Corporate Bond Fund",
      symbol: "ICICICORP",
      units: 450000,
      weight: null,
    },
    {
      asset_class: "Flexi Cap MF",
      average_cost: 52,
      id: seededUuid(userId, "holding-sharma-ppfas"),
      market_price: 60,
      market_value: 12_000_000,
      portfolio_id: portfolioIds.sharmaRetirement,
      security_name: "Parag Parikh Flexi Cap Fund",
      symbol: "PPFAS",
      units: 200000,
      weight: null,
    },
    {
      asset_class: "Index ETF",
      average_cost: 184,
      id: seededUuid(userId, "holding-sharma-niftybees"),
      market_price: 200,
      market_value: 11_000_000,
      portfolio_id: portfolioIds.sharmaRetirement,
      security_name: "Nippon Nifty 50 ETF",
      symbol: "NIFTYBEES",
      units: 55000,
      weight: null,
    },
    {
      asset_class: "Balanced Advantage Fund",
      average_cost: 35,
      id: seededUuid(userId, "holding-sharma-balanced"),
      market_price: 40,
      market_value: 10_000_000,
      portfolio_id: portfolioIds.sharmaRetirement,
      security_name: "HDFC Balanced Advantage Fund",
      symbol: "HDFCBALADV",
      units: 250000,
      weight: null,
    },
  ].map((holding) => ({
    ...holding,
    last_priced_at: timestampOffset(-1, 15, 30),
  }))

  const transactions: TransactionInsert[] = [
    {
      account_id: accountIds.patelGrowth,
      fees: 0,
      gross_amount: 58_200_000,
      id: seededUuid(userId, "transaction-patel-growth-deposit"),
      portfolio_id: portfolioIds.patelGrowth,
      price: 0,
      quantity: 0,
      settlement_at: dateOffset(-44),
      source: "Initial transfer",
      symbol: null,
      traded_at: timestampOffset(-45, 11, 0),
      transaction_type: "deposit",
    },
    {
      account_id: accountIds.patelGrowth,
      fees: 200_000,
      gross_amount: 48_000_000,
      id: seededUuid(userId, "transaction-patel-growth-buy"),
      portfolio_id: portfolioIds.patelGrowth,
      price: 48_000_000,
      quantity: 1,
      settlement_at: dateOffset(-42),
      source: "Advisor rebalance",
      symbol: "MODEL-BASKET",
      traded_at: timestampOffset(-43, 14, 30),
      transaction_type: "buy",
    },
    {
      account_id: accountIds.patelIncome,
      fees: 0,
      gross_amount: 34_100_000,
      id: seededUuid(userId, "transaction-patel-income-deposit"),
      portfolio_id: portfolioIds.patelIncome,
      price: 0,
      quantity: 0,
      settlement_at: dateOffset(-38),
      source: "Redemption proceeds",
      symbol: null,
      traded_at: timestampOffset(-39, 10, 15),
      transaction_type: "deposit",
    },
    {
      account_id: accountIds.patelIncome,
      fees: 100_000,
      gross_amount: 30_000_000,
      id: seededUuid(userId, "transaction-patel-income-buy"),
      portfolio_id: portfolioIds.patelIncome,
      price: 30_000_000,
      quantity: 1,
      settlement_at: dateOffset(-36),
      source: "Income bucket allocation",
      symbol: "DEBT-BASKET",
      traded_at: timestampOffset(-37, 15, 0),
      transaction_type: "buy",
    },
    {
      account_id: accountIds.iyerPreservation,
      fees: 0,
      gross_amount: 119_000_000,
      id: seededUuid(userId, "transaction-iyer-deposit"),
      portfolio_id: portfolioIds.iyerPreservation,
      price: 0,
      quantity: 0,
      settlement_at: dateOffset(-34),
      source: "Trust corpus transfer",
      symbol: null,
      traded_at: timestampOffset(-35, 10, 45),
      transaction_type: "deposit",
    },
    {
      account_id: accountIds.iyerPreservation,
      fees: 1_000_000,
      gross_amount: 97_000_000,
      id: seededUuid(userId, "transaction-iyer-buy"),
      portfolio_id: portfolioIds.iyerPreservation,
      price: 97_000_000,
      quantity: 1,
      settlement_at: dateOffset(-32),
      source: "Mandate launch",
      symbol: "PRESERVE-BASKET",
      traded_at: timestampOffset(-33, 13, 15),
      transaction_type: "buy",
    },
    {
      account_id: accountIds.mehtaGrowth,
      fees: 0,
      gross_amount: 54_350_000,
      id: seededUuid(userId, "transaction-mehta-deposit"),
      portfolio_id: portfolioIds.mehtaGrowth,
      price: 0,
      quantity: 0,
      settlement_at: dateOffset(-29),
      source: "Business distribution",
      symbol: null,
      traded_at: timestampOffset(-30, 9, 30),
      transaction_type: "deposit",
    },
    {
      account_id: accountIds.mehtaGrowth,
      fees: 350_000,
      gross_amount: 49_000_000,
      id: seededUuid(userId, "transaction-mehta-buy"),
      portfolio_id: portfolioIds.mehtaGrowth,
      price: 49_000_000,
      quantity: 1,
      settlement_at: dateOffset(-27),
      source: "Growth allocation",
      symbol: "ALPHA-BASKET",
      traded_at: timestampOffset(-28, 14, 15),
      transaction_type: "buy",
    },
    {
      account_id: accountIds.khandelwalIncome,
      fees: 0,
      gross_amount: 62_400_000,
      id: seededUuid(userId, "transaction-khandelwal-deposit"),
      portfolio_id: portfolioIds.khandelwalIncome,
      price: 0,
      quantity: 0,
      settlement_at: dateOffset(-24),
      source: "Treasury allocation",
      symbol: null,
      traded_at: timestampOffset(-25, 11, 45),
      transaction_type: "deposit",
    },
    {
      account_id: accountIds.khandelwalIncome,
      fees: 400_000,
      gross_amount: 54_000_000,
      id: seededUuid(userId, "transaction-khandelwal-buy"),
      portfolio_id: portfolioIds.khandelwalIncome,
      price: 54_000_000,
      quantity: 1,
      settlement_at: dateOffset(-22),
      source: "Yield ladder strategy",
      symbol: "INCOME-BASKET",
      traded_at: timestampOffset(-23, 16, 0),
      transaction_type: "buy",
    },
    {
      account_id: accountIds.sharmaRetirement,
      fees: 0,
      gross_amount: 38_250_000,
      id: seededUuid(userId, "transaction-sharma-deposit"),
      portfolio_id: portfolioIds.sharmaRetirement,
      price: 0,
      quantity: 0,
      settlement_at: dateOffset(-19),
      source: "Retirement account top-up",
      symbol: null,
      traded_at: timestampOffset(-20, 10, 0),
      transaction_type: "deposit",
    },
    {
      account_id: accountIds.sharmaRetirement,
      fees: 250_000,
      gross_amount: 33_000_000,
      id: seededUuid(userId, "transaction-sharma-buy"),
      portfolio_id: portfolioIds.sharmaRetirement,
      price: 33_000_000,
      quantity: 1,
      settlement_at: dateOffset(-17),
      source: "Retirement glide path",
      symbol: "RETIRE-BASKET",
      traded_at: timestampOffset(-18, 15, 15),
      transaction_type: "buy",
    },
  ]

  const tasks: TaskInsert[] = [
    {
      category: "compliance",
      client_id: clientIds.rajeshPatel,
      description: "Collect updated KYC pack and verify bank proof for all active family members.",
      due_at: timestampOffset(1, 17, 0),
      household_id: householdIds.patel,
      id: seededUuid(userId, "task-patel-kyc-refresh"),
      owner_id: userId,
      priority: "high",
      status: "todo",
      title: `Complete KYC refresh for ${investorIdentity.householdName}`,
    },
    {
      category: "advisory",
      client_id: clientIds.venkateshIyer,
      description: "Include succession options, trust overlays, and alternate income sleeve proposal.",
      due_at: timestampOffset(3, 16, 0),
      household_id: householdIds.iyer,
      id: seededUuid(userId, "task-iyer-proposal-pack"),
      owner_id: userId,
      priority: "high",
      status: "todo",
      title: "Prepare proposal pack for Iyer Legacy Trust",
    },
    {
      category: "review",
      client_id: clientIds.anilMehta,
      description: "Confirm agenda, rebalance summary, and new liquidity mandate talking points.",
      due_at: timestampOffset(5, 14, 30),
      household_id: householdIds.mehta,
      id: seededUuid(userId, "task-mehta-quarterly-review"),
      owner_id: userId,
      priority: "medium",
      status: "in_progress",
      title: "Schedule quarterly review for Mehta Entrepreneurs",
    },
    {
      category: "documentation",
      client_id: clientIds.priyaKhandelwal,
      description: "Signed mandate uploaded and tagged for client sharing.",
      due_at: timestampOffset(-1, 12, 0),
      household_id: householdIds.khandelwal,
      id: seededUuid(userId, "task-khandelwal-mandate"),
      owner_id: userId,
      priority: "medium",
      status: "done",
      title: "Upload signed mandate for Khandelwal Advisory Desk",
    },
    {
      category: "planning",
      client_id: clientIds.deepakSharma,
      description: "Update retirement projections with new expense assumptions and annuity options.",
      due_at: timestampOffset(7, 13, 0),
      household_id: householdIds.sharma,
      id: seededUuid(userId, "task-sharma-retirement"),
      owner_id: userId,
      priority: "medium",
      status: "todo",
      title: "Review retirement corpus projection for Sharma",
    },
    {
      category: "marketing",
      client_id: null,
      description: "Quarterly market commentary for client newsletter and advisory meetings.",
      due_at: timestampOffset(10, 18, 0),
      household_id: null,
      id: seededUuid(userId, "task-market-commentary"),
      owner_id: userId,
      priority: "low",
      status: "blocked",
      title: "Update market commentary for April review deck",
    },
    {
      category: "compliance",
      client_id: clientIds.meenaPatel,
      description: "Annual fee disclosure and suitability note need sign-off before Monday.",
      due_at: timestampOffset(2, 15, 30),
      household_id: householdIds.patel,
      id: seededUuid(userId, "task-patel-fee-disclosure"),
      owner_id: userId,
      priority: "high",
      status: "blocked",
      title: "File SEBI fee disclosure addendum",
    },
  ]

  const complianceRecords: ComplianceRecordInsert[] = [
    {
      completed_at: null,
      due_at: dateOffset(5),
      finding: `${investorIdentity.householdName} has an expiring suitability questionnaire.`,
      household_id: householdIds.patel,
      id: seededUuid(userId, "compliance-patel-suitability"),
      owner_id: userId,
      record_type: "SEBI Suitability Questionnaire",
      status: "pending",
    },
    {
      completed_at: null,
      due_at: dateOffset(10),
      finding: "Lakshmi Iyer KYC documents need re-verification.",
      household_id: householdIds.iyer,
      id: seededUuid(userId, "compliance-iyer-kyc"),
      owner_id: userId,
      record_type: "KYC Document Review",
      status: "in_review",
    },
    {
      completed_at: null,
      due_at: dateOffset(7),
      finding: "Four files in the advisory workspace are missing classification tags.",
      household_id: householdIds.khandelwal,
      id: seededUuid(userId, "compliance-khandelwal-retention"),
      owner_id: userId,
      record_type: "Document Retention Audit",
      status: "pending",
    },
    {
      completed_at: dateOffset(-18),
      due_at: dateOffset(15),
      finding: "Annual fee disclosure acknowledged by client.",
      household_id: householdIds.mehta,
      id: seededUuid(userId, "compliance-mehta-fee-disclosure"),
      owner_id: userId,
      record_type: "Fee Disclosure Confirmation",
      status: "approved",
    },
    {
      completed_at: null,
      due_at: dateOffset(20),
      finding: "Retirement risk assessment needs updating before the annual review.",
      household_id: householdIds.sharma,
      id: seededUuid(userId, "compliance-sharma-risk"),
      owner_id: userId,
      record_type: "Annual Risk Assessment",
      status: "pending",
    },
    {
      completed_at: dateOffset(-30),
      due_at: dateOffset(-30),
      finding: "AML screening completed successfully.",
      household_id: householdIds.patel,
      id: seededUuid(userId, "compliance-patel-aml"),
      owner_id: userId,
      record_type: "Anti-Money Laundering Check",
      status: "approved",
    },
    {
      completed_at: null,
      due_at: dateOffset(3),
      finding: "Portfolio concentration exceeds the internal guardrail for a single sector.",
      household_id: householdIds.iyer,
      id: seededUuid(userId, "compliance-iyer-suitability-review"),
      owner_id: userId,
      record_type: "Investment Suitability Review",
      status: "flagged",
    },
  ]

  const leadIds = {
    nexus: seededUuid(userId, "lead-nexus"),
    puneMedical: seededUuid(userId, "lead-pune-medical"),
    rajan: seededUuid(userId, "lead-rajan"),
    trivedi: seededUuid(userId, "lead-trivedi"),
    coastal: seededUuid(userId, "lead-coastal"),
  }

  const leads: LeadInsert[] = [
    {
      company_name: "Nexus Family Wealth",
      contact_name: "Arjun Reddy",
      email: "arjun@nexuswealth.in",
      id: leadIds.nexus,
      owner_id: userId,
      phone: "+91 90000 12345",
      score: 72,
      source: "referral",
      status: "converted",
    },
    {
      company_name: "Pune Medical Partners",
      contact_name: "Dr. Sanjay Kulkarni",
      email: "sanjay@pmpune.com",
      id: leadIds.puneMedical,
      owner_id: userId,
      phone: "+91 90000 12346",
      score: 45,
      source: "event",
      status: "converted",
    },
    {
      company_name: "Trivedi Holdings",
      contact_name: "Vikram Trivedi",
      email: "vikram@trivediholdings.com",
      id: leadIds.trivedi,
      owner_id: userId,
      phone: "+91 90000 12347",
      score: 85,
      source: "website",
      status: "qualified",
    },
    {
      company_name: "Rajan Group",
      contact_name: "Nirmala Rajan",
      email: "nirmala@rajangroup.in",
      id: leadIds.rajan,
      owner_id: userId,
      phone: "+91 90000 12348",
      score: 60,
      source: "referral",
      status: "contacted",
    },
    {
      company_name: "Coastal Investments",
      contact_name: "Srinivas Rao",
      email: "sri@coastalinv.com",
      id: leadIds.coastal,
      owner_id: userId,
      phone: "+91 90000 12349",
      score: 30,
      source: "cold_outreach",
      status: "new",
    },
  ]

  const opportunities: OpportunityInsert[] = [
    {
      expected_value: 32_000_000,
      household_id: null,
      id: seededUuid(userId, "opportunity-nexus"),
      lead_id: leadIds.nexus,
      notes: "Warm referral from the Bengaluru family office network.",
      owner_id: userId,
      probability: 35,
      stage: "qualifying",
      target_close_date: dateOffset(15),
      title: "Nexus Family Wealth Mandate",
    },
    {
      expected_value: 27_000_000,
      household_id: null,
      id: seededUuid(userId, "opportunity-pune-medical"),
      lead_id: leadIds.puneMedical,
      notes: "Founders looking for succession planning and treasury structuring.",
      owner_id: userId,
      probability: 30,
      stage: "qualifying",
      target_close_date: dateOffset(19),
      title: "Pune Medical Partners Advisory",
    },
    {
      expected_value: 41_000_000,
      household_id: householdIds.iyer,
      id: seededUuid(userId, "opportunity-iyer-expansion"),
      lead_id: null,
      notes: "Alternative investments add-on under the trust mandate.",
      owner_id: userId,
      probability: 62,
      stage: "proposal",
      target_close_date: dateOffset(7),
      title: "Iyer Legacy Expansion",
    },
    {
      expected_value: 16_000_000,
      household_id: householdIds.khandelwal,
      id: seededUuid(userId, "opportunity-khandelwal-retainer"),
      lead_id: null,
      notes: "Operations package for advisory branch rollout.",
      owner_id: userId,
      probability: 55,
      stage: "diligence",
      target_close_date: dateOffset(11),
      title: "Khandelwal Compliance Retainer",
    },
    {
      expected_value: 58_000_000,
      household_id: householdIds.patel,
      id: seededUuid(userId, "opportunity-patel-offshore"),
      lead_id: null,
      notes: "New family office portfolio sleeve with offshore allocation.",
      owner_id: userId,
      probability: 74,
      stage: "commitment",
      target_close_date: dateOffset(5),
      title: `${investorIdentity.reviewSubjectLabel} Strategic Allocation`,
    },
    {
      expected_value: 24_000_000,
      household_id: householdIds.mehta,
      id: seededUuid(userId, "opportunity-mehta-liquidity"),
      lead_id: null,
      notes: "Treasury and debt allocation refresh approved by founders.",
      owner_id: userId,
      probability: 100,
      stage: "won",
      target_close_date: dateOffset(2),
      title: "Mehta Liquidity Mandate",
    },
    {
      expected_value: 18_000_000,
      household_id: null,
      id: seededUuid(userId, "opportunity-rajan-lost"),
      lead_id: leadIds.rajan,
      notes: "Opportunity paused after internal treasury reshuffle.",
      owner_id: userId,
      probability: 0,
      stage: "lost",
      target_close_date: dateOffset(-6),
      title: "Rajan Treasury Advisory",
    },
  ]

  const meetings: MeetingInsert[] = [
    {
      ends_at: timestampOffset(3, 12, 0),
      household_id: householdIds.patel,
      id: seededUuid(userId, "meeting-patel-review"),
      location: `${investorIdentity.householdName}, ${investorIdentity.city}`,
      meeting_type: "review",
      notes: "Review Q1 performance and discuss rebalancing.",
      owner_id: userId,
      starts_at: timestampOffset(3, 11, 0),
      subject: `Quarterly Portfolio Review - ${investorIdentity.reviewSubjectLabel}`,
    },
    {
      ends_at: timestampOffset(5, 16, 30),
      household_id: householdIds.iyer,
      id: seededUuid(userId, "meeting-iyer-succession"),
      location: "Google Meet",
      meeting_type: "planning",
      notes: "Discuss trust structure options and capital-preservation overlays.",
      owner_id: userId,
      starts_at: timestampOffset(5, 15, 0),
      subject: "Succession Planning Discussion - Iyer",
    },
    {
      ends_at: timestampOffset(7, 13, 0),
      household_id: householdIds.mehta,
      id: seededUuid(userId, "meeting-mehta-proposal"),
      location: "WealthFlow Pro Office, Mumbai",
      meeting_type: "proposal",
      notes: "Present the new liquidity and mid-cap strategy deck.",
      owner_id: userId,
      starts_at: timestampOffset(7, 12, 0),
      subject: "Investment Proposal - Mehta",
    },
    {
      ends_at: timestampOffset(10, 12, 0),
      household_id: householdIds.sharma,
      id: seededUuid(userId, "meeting-sharma-retirement"),
      location: "Zoom",
      meeting_type: "review",
      notes: "Annual retirement planning review and withdrawal ladder discussion.",
      owner_id: userId,
      starts_at: timestampOffset(10, 11, 0),
      subject: "Retirement Review - Sharma",
    },
    {
      ends_at: timestampOffset(-2, 17, 30),
      household_id: householdIds.khandelwal,
      id: seededUuid(userId, "meeting-khandelwal-fee-sync"),
      location: "Pune Office",
      meeting_type: "ops",
      notes: "Closed out invoice aging review and renewed documentation checklist.",
      owner_id: userId,
      starts_at: timestampOffset(-2, 16, 30),
      subject: "Fee Renewal Sync - Khandelwal",
    },
  ]

  const documents: DocumentInsert[] = [
    {
      classification: "confidential",
      client_id: clientIds.rajeshPatel,
      document_type: "kyc",
      household_id: householdIds.patel,
      id: seededUuid(userId, "document-rajesh-kyc"),
      signed: true,
      storage_path: null,
      title: `${investorIdentity.displayName} - KYC Documents`,
      uploaded_by: userId,
      version_label: "v2",
    },
    {
      classification: "confidential",
      client_id: clientIds.meenaPatel,
      document_type: "identity",
      household_id: householdIds.patel,
      id: seededUuid(userId, "document-meena-pan"),
      signed: true,
      storage_path: null,
      title: "Household Member - Identity Pack",
      uploaded_by: userId,
      version_label: "v1",
    },
    {
      classification: "restricted",
      client_id: clientIds.venkateshIyer,
      document_type: "legal",
      household_id: householdIds.iyer,
      id: seededUuid(userId, "document-iyer-trust"),
      signed: true,
      storage_path: null,
      title: "Iyer Trust Deed",
      uploaded_by: userId,
      version_label: "v1",
    },
    {
      classification: "internal",
      client_id: clientIds.anilMehta,
      document_type: "agreement",
      household_id: householdIds.mehta,
      id: seededUuid(userId, "document-mehta-agreement"),
      signed: true,
      storage_path: null,
      title: "Mehta Advisory Agreement",
      uploaded_by: userId,
      version_label: "v3",
    },
    {
      classification: "client_shared",
      client_id: null,
      document_type: "billing",
      household_id: householdIds.khandelwal,
      id: seededUuid(userId, "document-khandelwal-fee"),
      signed: false,
      storage_path: null,
      title: "Khandelwal Fee Schedule 2026",
      uploaded_by: userId,
      version_label: "v1",
    },
    {
      classification: "client_shared",
      client_id: clientIds.deepakSharma,
      document_type: "planning",
      household_id: householdIds.sharma,
      id: seededUuid(userId, "document-sharma-plan"),
      signed: true,
      storage_path: null,
      title: "Sharma Retirement Plan",
      uploaded_by: userId,
      version_label: "v2",
    },
  ]

  const goals: GoalInsert[] = [
    {
      current_amount: 32_000_000,
      household_id: householdIds.patel,
      id: seededUuid(userId, "goal-patel-education"),
      priority: "high",
      status: "on_track",
      target_amount: 50_000_000,
      target_date: "2030-06-01",
      title: "Education Fund for Grandchildren",
    },
    {
      current_amount: 78_000_000,
      household_id: householdIds.iyer,
      id: seededUuid(userId, "goal-iyer-charity"),
      priority: "medium",
      status: "on_track",
      target_amount: 100_000_000,
      target_date: "2028-12-31",
      title: "Charitable Trust Corpus",
    },
    {
      current_amount: 42_000_000,
      household_id: householdIds.mehta,
      id: seededUuid(userId, "goal-mehta-expansion"),
      priority: "high",
      status: "at_risk",
      target_amount: 80_000_000,
      target_date: "2027-12-31",
      title: "Business Expansion Fund",
    },
    {
      current_amount: 18_000_000,
      household_id: householdIds.khandelwal,
      id: seededUuid(userId, "goal-khandelwal-office"),
      priority: "medium",
      status: "on_track",
      target_amount: 30_000_000,
      target_date: "2027-06-30",
      title: "Office Acquisition Fund",
    },
    {
      current_amount: 38_000_000,
      household_id: householdIds.sharma,
      id: seededUuid(userId, "goal-sharma-retirement"),
      priority: "high",
      status: "on_track",
      target_amount: 60_000_000,
      target_date: "2032-03-31",
      title: "Retirement Corpus",
    },
  ]

  const feeSchedules: FeeScheduleInsert[] = [
    {
      advisory_fee_bps: 75,
      billing_frequency: "quarterly",
      collection_status: "pending",
      household_id: householdIds.patel,
      id: seededUuid(userId, "fee-patel"),
      last_invoice_date: "2025-12-31",
      next_invoice_date: "2026-03-31",
    },
    {
      advisory_fee_bps: 50,
      billing_frequency: "quarterly",
      collection_status: "pending",
      household_id: householdIds.iyer,
      id: seededUuid(userId, "fee-iyer"),
      last_invoice_date: "2025-12-31",
      next_invoice_date: "2026-03-31",
    },
    {
      advisory_fee_bps: 100,
      billing_frequency: "monthly",
      collection_status: "collected",
      household_id: householdIds.mehta,
      id: seededUuid(userId, "fee-mehta"),
      last_invoice_date: "2026-02-28",
      next_invoice_date: "2026-03-31",
    },
    {
      advisory_fee_bps: 65,
      billing_frequency: "quarterly",
      collection_status: "overdue",
      household_id: householdIds.khandelwal,
      id: seededUuid(userId, "fee-khandelwal"),
      last_invoice_date: "2025-12-31",
      next_invoice_date: "2026-03-31",
    },
    {
      advisory_fee_bps: 60,
      billing_frequency: "annual",
      collection_status: "pending",
      household_id: householdIds.sharma,
      id: seededUuid(userId, "fee-sharma"),
      last_invoice_date: "2025-03-31",
      next_invoice_date: "2026-03-31",
    },
  ]

  const communicationLogs: CommunicationLogInsert[] = [
    {
      channel: "email",
      client_id: clientIds.rajeshPatel,
      household_id: householdIds.patel,
      id: seededUuid(userId, "comm-patel-email"),
      logged_at: timestampOffset(-1, 9, 30),
      owner_id: userId,
      subject: "Quarterly review agenda",
      summary: "Shared performance snapshot and agenda for the upcoming family office review.",
    },
    {
      channel: "phone",
      client_id: clientIds.venkateshIyer,
      household_id: householdIds.iyer,
      id: seededUuid(userId, "comm-iyer-phone"),
      logged_at: timestampOffset(-2, 12, 0),
      owner_id: userId,
      subject: "Trust distribution call",
      summary: "Discussed beneficiary cash-flow timing and required trustee approvals.",
    },
    {
      channel: "whatsapp",
      client_id: clientIds.anilMehta,
      household_id: householdIds.mehta,
      id: seededUuid(userId, "comm-mehta-whatsapp"),
      logged_at: timestampOffset(-1, 18, 15),
      owner_id: userId,
      subject: "Proposal follow-up",
      summary: "Sent the liquidity deck and confirmed next week's investment proposal slot.",
    },
    {
      channel: "meeting",
      client_id: clientIds.priyaKhandelwal,
      household_id: householdIds.khandelwal,
      id: seededUuid(userId, "comm-khandelwal-meeting"),
      logged_at: timestampOffset(-3, 16, 30),
      owner_id: userId,
      subject: "Billing review",
      summary: "Reviewed open invoices, fee cadence, and client-sharing requirements.",
    },
    {
      channel: "sms",
      client_id: clientIds.deepakSharma,
      household_id: householdIds.sharma,
      id: seededUuid(userId, "comm-sharma-sms"),
      logged_at: timestampOffset(0, 8, 45),
      owner_id: userId,
      subject: "Meeting reminder",
      summary: "Sent a reminder for the retirement review and requested updated expense inputs.",
    },
    {
      channel: "email",
      client_id: clientIds.lakshmiIyer,
      household_id: householdIds.iyer,
      id: seededUuid(userId, "comm-iyer-kyc-email"),
      logged_at: timestampOffset(-4, 10, 20),
      owner_id: userId,
      subject: "Pending KYC documents",
      summary: "Requested updated address proof and PAN scan to close the KYC review.",
    },
  ]

  return {
    accounts,
    clients,
    communicationLogs,
    complianceRecords,
    documents,
    feeSchedules,
    goals,
    holdings,
    households,
    leads,
    meetings,
    opportunities,
    portfolios,
    profile,
    tasks,
    transactions,
  }
}
